sudo: required
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

rust:
- nightly
- beta
- stable
- 1.20.0
- 1.19.0
- 1.18.0
- 1.17.0

matrix:
  allow_failures:
  - rust: nightly

before_script:
- fallocate -l 128M test.img
- '[[ "$TRAVIS_RUST_VERSION" != "stable" ]] || rustup component add clippy-preview'

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""

script: 
- '[[ "$TRAVIS_RUST_VERSION" != "stable" ]] || cargo clippy -- -D warnings'
- cargo build --verbose
- sudo -E  env "PATH=$PATH" cargo test --verbose

jobs:
  include:
  - script: cd losetup && cargo build --verbose
    rust: stable
