[package]
name = "loopdev"
description = "Setup and control loop devices"
version = "0.1.1"
authors = ["Michael Daffin <michael@daffin.io>"]
license = "MIT"
documentation = "https://disconnected.systems/loopdev/loopdev/"
homepage = "https://disconnected.systems/loopdev/loopdev/"
repository = "https://github.com/mdaffin/loopdev"
readme = "README.md"
keywords = ["loop", "losetup"]

[dependencies]
errno = "0.1"
libc = "0.2"
docopt = "0.6"
rustc-serialize = "0.3"
