[package]
name = "loopdev"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]

[dependencies]
libc = "0.2"
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
