[package]
authors = ["Michael Daffin <michael@daffin.io>"]
name = "losetup"
version = "0.2.0"
description = "Setup and control loopback devices"

[dependencies]
clap = "2.23.3"

[dependencies.loopdev]
optional = false
path = ".."
