[package]
authors = ["Michael Daffin <michael@daffin.io>"]
name = "losetup"
version = "0.1.2"

[dependencies]
clap = "2.23.3"
docopt = "0.7.0"
rustc-serialize = "0.3.24"

[dependencies.loopdev]
optional = false
path = ".."
